In [2]:
from sklearn import tree
import pandas as pd

In [4]:
train_data = pd.read_csv("tokyo/train_files/stock_prices.csv")
X = train_data["Close"]
y = train_data["Target"]
clf = tree.DecisionTreeRegressor()
train_data.describe()

SecuritiesCode          Open          High           Low         Close  \
count    2.332531e+06  2.324923e+06  2.324923e+06  2.324923e+06  2.324923e+06   
mean     5.894835e+03  2.594511e+03  2.626540e+03  2.561227e+03  2.594023e+03   
std      2.404161e+03  3.577192e+03  3.619363e+03  3.533494e+03  3.576538e+03   
min      1.301000e+03  1.400000e+01  1.500000e+01  1.300000e+01  1.400000e+01   
25%      3.891000e+03  1.022000e+03  1.035000e+03  1.009000e+03  1.022000e+03   
50%      6.238000e+03  1.812000e+03  1.834000e+03  1.790000e+03  1.811000e+03   
75%      7.965000e+03  3.030000e+03  3.070000e+03  2.995000e+03  3.030000e+03   
max      9.997000e+03  1.099500e+05  1.105000e+05  1.072000e+05  1.095500e+05   

             Volume  AdjustmentFactor  ExpectedDividend        Target  
count  2.332531e+06      2.332531e+06      18865.000000  2.332293e+06  
mean   6.919366e+05      1.000508e+00         22.017730  4.450962e-04  
std    3.911256e+06      6.773040e-02         29.882453  2.339879e-02  
min    0.000000e+00      1.000000e-01          0.000000 -5.785414e-01  
25%    3.030000e+04      1.000000e+00          5.000000 -1.049869e-02  
50%    1.071000e+05      1.000000e+00         15.000000  0.000000e+00  
75%    4.021000e+05      1.000000e+00         30.000000  1.053159e-02  
max    6.436540e+08      2.000000e+01       1070.000000  1.119512e+00

In [6]:
import os
import pandas as pd
import numpy as np
import gc
import matplotlib.pyplot as plt
import tensorflow as tf
import json
import numpy as np
from scipy.special import comb
from itertools import combinations

class CombinatorialPurgedGroupKFold():
    def __init__(self, n_splits = 6, n_test_splits = 2, purge = 1, pctEmbargo = 0.01, **kwargs):
        self.n_splits = n_splits
        self.n_test_splits = n_test_splits
        self.purge = purge
        self.pctEmbargo = pctEmbargo
        
    def split(self, X, y = None, groups = None):
        if groups is None:
            raise ValueError(
                "The 'groups' parameter should not be None")
            
        u, ind = np.unique(groups, return_index = True)
        unique_groups = u[np.argsort(ind)]
        n_groups = len(unique_groups)
        group_dict = {}
        for idx in range(len(X)):
            if groups[idx] in group_dict:
                group_dict[groups[idx]].append(idx)
            else:
                group_dict[groups[idx]] = [idx]
                
        n_folds = comb(self.n_splits, self.n_test_splits, exact = True)
        if n_folds > n_groups:
            raise ValueError(
                ("Cannot have number of folds={0} greater than"
                 " the number of groups={1}").format(n_folds,
                                                     n_groups))
            
        mbrg = int(n_groups * self.pctEmbargo)
        if mbrg < 0:
            raise ValueError(
                "The number of 'embargoed' groups should not be negative")
        
        split_dict = {}
        group_test_size = n_groups // self.n_splits
        for split in range(self.n_splits):
            if split == self.n_splits - 1:
                split_dict[split] = unique_groups[int(split * group_test_size):].tolist()
            else:
                split_dict[split] = unique_groups[int(split * group_test_size):int((split + 1) * group_test_size)].tolist()
        
        for test_splits in combinations(range(self.n_splits), self.n_test_splits):
            test_groups = []
            banned_groups = []
            for split in test_splits:
                test_groups += split_dict[split]
                banned_groups += unique_groups[split_dict[split][0] - self.purge:split_dict[split][0]].tolist()
                banned_groups += unique_groups[split_dict[split][-1] + 1:split_dict[split][-1] + self.purge + mbrg + 1].tolist()
            train_groups = [i for i in unique_groups if (i not in banned_groups) and (i not in test_groups)]

            train_idx = []
            test_idx = []
            for train_group in train_groups:
                train_idx += group_dict[train_group]
            for test_group in test_groups:
                test_idx += group_dict[test_group]
            yield train_idx, test_idx

2022-06-03 00:02:27.226575: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-03 00:02:27.226740: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [37]:
import sys
record_defaults = [999,999,999,999]
dataset = tf.data.experimental.CsvDataset("missing.csv", record_defaults)

dataset = dataset.map(lambda *items: tf.stack(items))
for line in dataset:
    print(line)


tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor([999   2   3   4], shape=(4,), dtype=int32)
tf.Tensor([  1 999   3   4], shape=(4,), dtype=int32)
tf.Tensor([  1   2 999   4], shape=(4,), dtype=int32)
tf.Tensor([  1   2   3 999], shape=(4,), dtype=int32)
tf.Tensor([999 999 999 999], shape=(4,), dtype=int32)


In [13]:
for line in dataset:
  print(line)

(<tf.Tensor: shape=(), dtype=int32, numpy=1>, <tf.Tensor: shape=(), dtype=int32, numpy=2>, <tf.Tensor: shape=(), dtype=int32, numpy=3>, <tf.Tensor: shape=(), dtype=int32, numpy=4>)
(<tf.Tensor: shape=(), dtype=int32, numpy=999>, <tf.Tensor: shape=(), dtype=int32, numpy=2>, <tf.Tensor: shape=(), dtype=int32, numpy=3>, <tf.Tensor: shape=(), dtype=int32, numpy=4>)
(<tf.Tensor: shape=(), dtype=int32, numpy=1>, <tf.Tensor: shape=(), dtype=int32, numpy=999>, <tf.Tensor: shape=(), dtype=int32, numpy=3>, <tf.Tensor: shape=(), dtype=int32, numpy=4>)
(<tf.Tensor: shape=(), dtype=int32, numpy=1>, <tf.Tensor: shape=(), dtype=int32, numpy=2>, <tf.Tensor: shape=(), dtype=int32, numpy=999>, <tf.Tensor: shape=(), dtype=int32, numpy=4>)
(<tf.Tensor: shape=(), dtype=int32, numpy=1>, <tf.Tensor: shape=(), dtype=int32, numpy=2>, <tf.Tensor: shape=(), dtype=int32, numpy=3>, <tf.Tensor: shape=(), dtype=int32, numpy=999>)
(<tf.Tensor: shape=(), dtype=int32, numpy=999>, <tf.Tensor: shape=(), dtype=int32, nump